name: Deploy to GitHub Pages[cite: 1]

on:
  push:
    branches:
      - main[cite: 1]

permissions:
  contents: read[cite: 1]
  pages: write[cite: 1]
  id-token: write[cite: 1]

concurrency:
  group: "pages"[cite: 1]
  cancel-in-progress: true[cite: 1]

jobs:
  deploy:
    environment:
      name: github-pages[cite: 1]
      url: ${{ steps.deployment.outputs.page_url }}[cite: 1]
    runs-on: ubuntu-latest[cite: 1]
    steps:
      - name: Checkout[cite: 1]
        uses: actions/checkout@v4[cite: 1]
      - name: Set up Node[cite: 1]
        uses: actions/setup-node@v4[cite: 1]
        with:
          node-version: 20[cite: 1]
          cache: 'npm'[cite: 1]
      - name: Install dependencies[cite: 1]
        run: npm ci
      - name: Build[cite: 1]
        run: npm run build[cite: 1]
      - name: Setup Pages[cite: 1]
        uses: actions/configure-pages@v4[cite: 1]
      - name: Upload artifact[cite: 1]
        uses: actions/upload-pages-artifact@v3[cite: 1]
        with:
          path: './dist'[cite: 1]
      - name: Deploy to GitHub Pages[cite: 1]
        id: deployment[cite: 1]
        uses: actions/deploy-pages@v4[cite: 1]
